import { colors } from '../../theme';
import type { EditorTool, JournalPage } from './types';

export const editorTools: EditorTool[] = [
  { kind: 'paper', label: '背景', icon: '▧', description: '切换页面背景' },
  { kind: 'text', label: '文字', icon: 'T', description: '添加排版文字' },
  { kind: 'sticker', label: '贴纸', icon: '★', description: '添加装饰素材' },
  { kind: 'page', label: '分页', icon: '□', description: '管理手账分页' },
  { kind: 'favorite', label: '收藏', icon: '♡', description: '收藏当前页面' },
  { kind: 'image', label: '图片', icon: '▣', description: '上传本地照片' },
];

export const sampleJournalPage: JournalPage = {
  id: 'page-weekend-date',
  title: '周末约会',
  folderName: '五月日常',
  paper: {
    id: 'background-texture-lined',
    name: '横线纸',
    kind: 'lined',
    color: '#FFFDF7',
    secondaryColor: '#EADFD2',
    accentColor: '#C9B7A3',
    backgroundType: 'texture',
    fitMode: 'tile',
  },
  size: {
    width: 300,
    height: 400,
  },
  updatedAtLabel: '今天 20:18',
  saveState: 'saved',
  elements: [
    {
      id: 'photo-01',
      kind: 'image',
      name: '散步照片',
      sourceLabel: '本地照片',
      tintColor: colors.accent,
      frame: {
        x: 24,
        y: 34,
        width: 128,
        height: 118,
        rotation: -4,
      },
      zIndex: 1,
      opacity: 1,
    },
    {
      id: 'text-01',
      kind: 'text',
      name: '心情文字',
      content: '晚风很好\n和你散步的时候，时间慢了下来。',
      fontSize: 15,
      color: colors.text,
      backgroundColor: 'transparent',
      fontId: 'system-default',
      fontFamily: undefined,
      fontName: '系统默认',
      fontStyle: 'normal',
      fontWeight: '700',
      frame: {
        x: 132,
        y: 246,
        width: 164,
        height: 116,
        rotation: 0,
      },
      zIndex: 2,
      opacity: 1,
    },
    {
      id: 'sticker-01',
      kind: 'sticker',
      name: '爱心贴纸',
      stickerId: 'sticker-emotion-heart',
      label: '♥',
      color: colors.primary,
      backgroundColor: 'transparent',
      imageUri: undefined,
      sourceUrl: 'https://api.iconify.design/fluent-emoji-flat/red-heart.svg',
      frame: {
        x: 224,
        y: 86,
        width: 64,
        height: 64,
        rotation: 8,
      },
      zIndex: 3,
      opacity: 1,
    },
  ],
};
